{{- if .Values.ingress.enabled -}}
{{- $serviceName := .Values.service.name | default (printf "%s-service" (include "ndp-ep-api.fullname" .)) -}}
{{- $ingressName := .Values.ingress.name | default (printf "%s-ingress" (include "ndp-ep-api.fullname" .)) -}}
{{- $path := .Values.ingress.path | default .Values.rootPath.value -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "ndp-ep-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ $path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ .Values.service.port }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
