apiVersion: apps/v1
kind: Deployment
metadata:
  name: rexec-broker
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "broker.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: rexec-broker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: client
              containerPort: {{ .Values.ports.client }}
              protocol: TCP
            - name: server
              containerPort: {{ .Values.ports.server }}
              protocol: TCP
            - name: control
              containerPort: {{ .Values.ports.control }}
              protocol: TCP
          env:
            - name: AUTH_API_URL
              value: {{ default .Values.global.authApiUrl .Values.authApiUrl | quote }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
